
// query

function httpRequest(callback) {

	var stocks = localStorage.stocks || 'sh000001';
	var url = 'https://apishot';

    var xhr = new XMLHttpRequest();
    xhr.open("GET", url, true);
    xhr.onreadystatechange = function() {
        if (xhr.readyState == 4) {
            callback(xhr.responseText);
        }
    }
    xhr.send();
}

// render

function showResult(result) {



	// document.getElementById('stock').innerHTML = table;
	var jsData = JSON.parse(result);
	if(jsData.code == 200){
		var countrys = jsData.countrys;
		var sync_time = jsData.msg;
		var base='';
		var tb='';
		countrys.forEach(function(item){
			if(item.base ==true){

				// base+='<div class="item" >';
				// base+='<div class="leftbox"><image class="img" src="'+item.img_url+'"/></div>';
				// base+='<div class="midbox">';
				// base+='<div class="top">'+item.name +'</div>';
				// base+='<div class="bottom">'+item.us_en+'</div>';
				// base+='</div>';
				// base+='<div class="rightbox"><input class="display"  name="'+item.name+'" value="'+item.display+'" id="base_input">  </div><input class="val"  name="" value="'+item.value+'" type="hidden" id="base_input_val">';
				// base+='</div>';
			}
			//if(item.favorite ==true){

				// tb+='<div class="item" id="item_'+item.name+'">';
				// tb+='<div class="leftbox"><image class="img" src="'+item.img_url+'"/></div>';
				// tb+='<div class="midbox">';
				// tb+='<div class="top">'+item.name +'</div>';
				// tb+='<div class="bottom">'+item.us_en+'</div>';
				// tb+='</div>';
				// tb+='<div class="rightbox"><input class="display" name="'+item.name+'" value="'+item.display+'" id="'+item.name+'"></div><input class="val"  name="" value="'+item.value+'" type="hidden" id="'+item.name+'_val">';
				// tb+='</div>';

			// }else{
			// 	var item = 'item_'+item.name
			// 	document.getElementById(item).style.display="none";
			// }
		})
		//base += '</table>';
		//tb += '</table>';
		// document.getElementById('base').innerHTML = base;
		// document.getElementById('countrys').innerHTML = tb;
		document.getElementById('sync_time').innerHTML = '- '+sync_time+' (utc+8) -';
		//document.write("<script>function base_input() {console.log(1);}</script>");
	}

	
}


httpRequest(showResult);

document.getElementById('base_input').oninput = function(){
	var r = document.getElementById('base_input').value;
  console.log(r);
}



document.getElementById('base_input').oninput = function(){
	var input_dis = document.getElementById('base_input').value;
	console.log(input_dis);
	var input_val = document.getElementById('base_input_val').value;
	var rate = input_dis / input_val;
    
	var countrys_val= document.getElementsByClassName("val")
	var countrys_dis= document.getElementsByClassName("display")
	for(var i=1;i<countrys_dis.length;i++){ 
	  countrys_dis[i].value = parseFloat((countrys_val[i].value * input_dis).toFixed(4));
	}
}



document.getElementById('AED').oninput = function(){
	var input_dis = document.getElementById('AED').value;
	var input_val = document.getElementById('AED_val').value;
	console.log(input_dis);

	var rate = input_dis / input_val;

	var base_val = document.getElementById('base_input_val').value;
	var base_dis = parseFloat((rate * base_val).toFixed(4));
	document.getElementById('base_input').value = base_dis;


	var countrys_val= document.getElementsByClassName("val")
	var countrys_dis= document.getElementsByClassName("display")
	for(var i=1;i<countrys_dis.length;i++){ 
		if(countrys_dis[i].name != 'AED'){
			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));
		}
	}  
}

document.getElementById('FJD').oninput =function(){	var input_dis = document.getElementById('FJD').value;	var input_val = document.getElementById('FJD_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'FJD'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('BGN').oninput =function(){	var input_dis = document.getElementById('BGN').value;	var input_val = document.getElementById('BGN_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'BGN'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('BRL').oninput =function(){	var input_dis = document.getElementById('BRL').value;	var input_val = document.getElementById('BRL_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'BRL'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('INR').oninput =function(){	var input_dis = document.getElementById('INR').value;	var input_val = document.getElementById('INR_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'INR'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('CNY').oninput =function(){	var input_dis = document.getElementById('CNY').value;	var input_val = document.getElementById('CNY_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'CNY'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('PYG').oninput =function(){	var input_dis = document.getElementById('PYG').value;	var input_val = document.getElementById('PYG_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'PYG'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('UAH').oninput =function(){	var input_dis = document.getElementById('UAH').value;	var input_val = document.getElementById('UAH_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'UAH'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('ARS').oninput =function(){	var input_dis = document.getElementById('ARS').value;	var input_val = document.getElementById('ARS_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'ARS'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('EGP').oninput =function(){	var input_dis = document.getElementById('EGP').value;	var input_val = document.getElementById('EGP_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'EGP'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('SEK').oninput =function(){	var input_dis = document.getElementById('SEK').value;	var input_val = document.getElementById('SEK_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'SEK'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('NZD').oninput =function(){	var input_dis = document.getElementById('NZD').value;	var input_val = document.getElementById('NZD_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'NZD'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('AED').oninput =function(){	var input_dis = document.getElementById('AED').value;	var input_val = document.getElementById('AED_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'AED'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('SAR').oninput =function(){	var input_dis = document.getElementById('SAR').value;	var input_val = document.getElementById('SAR_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'SAR'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('NOK').oninput =function(){	var input_dis = document.getElementById('NOK').value;	var input_val = document.getElementById('NOK_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'NOK'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('KRW').oninput =function(){	var input_dis = document.getElementById('KRW').value;	var input_val = document.getElementById('KRW_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'KRW'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('MYR').oninput =function(){	var input_dis = document.getElementById('MYR').value;	var input_val = document.getElementById('MYR_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'MYR'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('PKR').oninput =function(){	var input_dis = document.getElementById('PKR').value;	var input_val = document.getElementById('PKR_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'PKR'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('CZK').oninput =function(){	var input_dis = document.getElementById('CZK').value;	var input_val = document.getElementById('CZK_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'CZK'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('IDR').oninput =function(){	var input_dis = document.getElementById('IDR').value;	var input_val = document.getElementById('IDR_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'IDR'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('AUD').oninput =function(){	var input_dis = document.getElementById('AUD').value;	var input_val = document.getElementById('AUD_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'AUD'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('COP').oninput =function(){	var input_dis = document.getElementById('COP').value;	var input_val = document.getElementById('COP_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'COP'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('CHF').oninput =function(){	var input_dis = document.getElementById('CHF').value;	var input_val = document.getElementById('CHF_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'CHF'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('DOP').oninput =function(){	var input_dis = document.getElementById('DOP').value;	var input_val = document.getElementById('DOP_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'DOP'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('CAD').oninput =function(){	var input_dis = document.getElementById('CAD').value;	var input_val = document.getElementById('CAD_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'CAD'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('ILS').oninput =function(){	var input_dis = document.getElementById('ILS').value;	var input_val = document.getElementById('ILS_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'ILS'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('ISK').oninput =function(){	var input_dis = document.getElementById('ISK').value;	var input_val = document.getElementById('ISK_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'ISK'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('GBP').oninput =function(){	var input_dis = document.getElementById('GBP').value;	var input_val = document.getElementById('GBP_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'GBP'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('SGD').oninput =function(){	var input_dis = document.getElementById('SGD').value;	var input_val = document.getElementById('SGD_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'SGD'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('UYU').oninput =function(){	var input_dis = document.getElementById('UYU').value;	var input_val = document.getElementById('UYU_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'UYU'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('CLP').oninput =function(){	var input_dis = document.getElementById('CLP').value;	var input_val = document.getElementById('CLP_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'CLP'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('PHP').oninput =function(){	var input_dis = document.getElementById('PHP').value;	var input_val = document.getElementById('PHP_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'PHP'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('GTQ').oninput =function(){	var input_dis = document.getElementById('GTQ').value;	var input_val = document.getElementById('GTQ_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'GTQ'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('MXN').oninput =function(){	var input_dis = document.getElementById('MXN').value;	var input_val = document.getElementById('MXN_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'MXN'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('HRK').oninput =function(){	var input_dis = document.getElementById('HRK').value;	var input_val = document.getElementById('HRK_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'HRK'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('KZT').oninput =function(){	var input_dis = document.getElementById('KZT').value;	var input_val = document.getElementById('KZT_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'KZT'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('TWD').oninput =function(){	var input_dis = document.getElementById('TWD').value;	var input_val = document.getElementById('TWD_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'TWD'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('USD').oninput =function(){	var input_dis = document.getElementById('USD').value;	var input_val = document.getElementById('USD_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'USD'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('HKD').oninput =function(){	var input_dis = document.getElementById('HKD').value;	var input_val = document.getElementById('HKD_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'HKD'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('PAB').oninput =function(){	var input_dis = document.getElementById('PAB').value;	var input_val = document.getElementById('PAB_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'PAB'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('PLN').oninput =function(){	var input_dis = document.getElementById('PLN').value;	var input_val = document.getElementById('PLN_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'PLN'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('HUF').oninput =function(){	var input_dis = document.getElementById('HUF').value;	var input_val = document.getElementById('HUF_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'HUF'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('JPY').oninput =function(){	var input_dis = document.getElementById('JPY').value;	var input_val = document.getElementById('JPY_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'JPY'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('BSD').oninput =function(){	var input_dis = document.getElementById('BSD').value;	var input_val = document.getElementById('BSD_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'BSD'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('DKK').oninput =function(){	var input_dis = document.getElementById('DKK').value;	var input_val = document.getElementById('DKK_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'DKK'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('TRY').oninput =function(){	var input_dis = document.getElementById('TRY').value;	var input_val = document.getElementById('TRY_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'TRY'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('PEN').oninput =function(){	var input_dis = document.getElementById('PEN').value;	var input_val = document.getElementById('PEN_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'PEN'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('RON').oninput =function(){	var input_dis = document.getElementById('RON').value;	var input_val = document.getElementById('RON_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'RON'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('ZAR').oninput =function(){	var input_dis = document.getElementById('ZAR').value;	var input_val = document.getElementById('ZAR_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'ZAR'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('MVR').oninput =function(){	var input_dis = document.getElementById('MVR').value;	var input_val = document.getElementById('MVR_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'MVR'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('EUR').oninput =function(){	var input_dis = document.getElementById('EUR').value;	var input_val = document.getElementById('EUR_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'EUR'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('THB').oninput =function(){	var input_dis = document.getElementById('THB').value;	var input_val = document.getElementById('THB_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'THB'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}
document.getElementById('RUB').oninput =function(){	var input_dis = document.getElementById('RUB').value;	var input_val = document.getElementById('RUB_val').value;	var rate = input_dis / input_val;	var base_val = document.getElementById('base_input_val').value;	var base_dis = parseFloat((rate * base_val).toFixed(4));	document.getElementById('base_input').value = base_dis;	var countrys_val= document.getElementsByClassName('val');	var countrys_dis= document.getElementsByClassName('display');	for(var i=1;i<countrys_dis.length;i++){		if(countrys_dis[i].name != 'RUB'){			countrys_dis[i].value = parseFloat((countrys_val[i].value * base_dis).toFixed(4));		}	}}


